## Financial Analysis: Microsoft, Tesla, and Apple (2023–2025)

### Introduction

This report analyzes the financial performance of Microsoft, Tesla, and Apple from fiscal years 2023 to 2025. The analysis focuses on five financial metrics: total revenue, net income, total assets, total liabilities, and operating cash flow. Financial data were extracted from the companies' annual Form 10-K filings and analyzed using Python and the pandas library to calculate year-over-year changes and compare financial trends.

### Data Loading

The financial dataset was imported from a CSV file using the pandas library.

In [1]:
import pandas as pd

df = pd.read_csv("k10forge.csv")
df.head()

,company,year,total revenue,net income,total assets,total liabilities,operating cash flow
0,microsoft,2023,211915,72361,411976,205753,87582
1,microsoft,2024,245122,88136,512163,243686,118548
2,microsoft,2025,281724,101832,619003,275524,136162
3,tesla,2023,96773,14974,106618,43009,13256
4,tesla,2024,97690,7153,122070,48390,14923

### Data Validation

Before performing financial calculations, the dataset was inspected to verify its structure, data types, and missing values.

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              9 non-null      str
 1   year                 9 non-null      int64
 2   total revenue        9 non-null      int64
 3   net income           9 non-null      int64
 4   total assets         9 non-null      int64
 5   total liabilities    9 non-null      int64
 6   operating cash flow  9 non-null      int64
dtypes: int64(6), str(1)
memory usage: 636.0 bytes

### Financial Calculations

The following calculations examine year-over-year financial changes, profitability, and the relationship between total liabilities and total assets.

#### Revenue Growth

Revenue growth measures the percentage change in revenue compared with the previous fiscal year.

$$
\text{Revenue Growth} = \frac{\text{Current Year Revenue} - \text{Previous Year Revenue}}{\text{Previous Year Revenue}} \times 100\%
$$

In [3]:
df = df.sort_values(["company", "year"])

df["revenue growth (%)"] = (
    df.groupby("company")["total revenue"].pct_change() * 100
)

df[["company", "year", "total revenue", "revenue growth (%)"]]

     company  year  total revenue  revenue growth (%)
6      apple  2023         383285                 NaN
7      apple  2024         391035            2.021994
8      apple  2025         416161            6.425512
0  microsoft  2023         211915                 NaN
1  microsoft  2024         245122           15.669962
2  microsoft  2025         281724           14.932156
3      tesla  2023          96773                 NaN
4      tesla  2024          97690            0.947578
5      tesla  2025          94827           -2.930699

#### Net Income Growth

Net income growth measures the percentage change in a company's net income compared with the previous fiscal year.

$$
\text{Net Income Growth} = \frac{\text{Current Year Net Income} - \text{Previous Year Net Income}}{\text{Previous Year Net Income}} \times 100\%
$$

In [4]:
df["net income growth (%)"] = (
    df.groupby("company")["net income"].pct_change() * 100
)

df[["company", "year", "net income", "net income growth (%)"]]

     company  year  net income  net income growth (%)
6      apple  2023       96995                    NaN
7      apple  2024       93736              -3.359967
8      apple  2025      112010              19.495178
0  microsoft  2023       72361                    NaN
1  microsoft  2024       88136              21.800417
2  microsoft  2025      101832              15.539621
3      tesla  2023       14974                    NaN
4      tesla  2024        7153             -52.230533
5      tesla  2025        3855             -46.106529

#### Net Profit Margin

Net profit margin measures the percentage of revenue that remains as net income after expenses.

$$
\text{Net Profit Margin} = \frac{\text{Net Income}}{\text{Total Revenue}} \times 100\%
$$

In [5]:
df["profit margin (%)"] = df["net income"] / df["total revenue"] * 100

df[["company", "year", "profit margin (%)"]]

     company  year  profit margin (%)
6      apple  2023          25.306234
7      apple  2024          23.971256
8      apple  2025          26.915064
0  microsoft  2023          34.146238
1  microsoft  2024          35.955973
2  microsoft  2025          36.146015
3      tesla  2023          15.473324
4      tesla  2024           7.322141
5      tesla  2025           4.065298

#### Operating Cash Flow Growth

Operating cash flow growth measures the percentage change in cash generated from operating activities compared with the previous fiscal year.

$$
\text{Operating Cash Flow Growth} =
\frac{\text{Current Year Operating Cash Flow} - \text{Previous Year Operating Cash Flow}}
{\text{Previous Year Operating Cash Flow}}
\times 100\%
$$

In [6]:
df["cash flow growth (%)"] = (
    df.groupby("company")["operating cash flow"].pct_change() * 100
)

df[["company", "year", "operating cash flow", "cash flow growth (%)"]]

     company  year  operating cash flow  cash flow growth (%)
6      apple  2023               122151                   NaN
7      apple  2024               110543             -9.502992
8      apple  2025               118254              6.975566
0  microsoft  2023                87582                   NaN
1  microsoft  2024               118548             35.356580
2  microsoft  2025               136162             14.858117
3      tesla  2023                13256                   NaN
4      tesla  2024                14923             12.575438
5      tesla  2025                14747             -1.179388

#### Liabilities-to-Assets Ratio

The liabilities-to-assets ratio measures the proportion of a company's total assets that corresponds to its total liabilities.

$$
\text{Liabilities-to-Assets Ratio} =
\frac{\text{Total Liabilities}}{\text{Total Assets}}
\times 100\%
$$

In [7]:
df["liabilities to assets (%)"] = (
    df["total liabilities"] / df["total assets"] * 100
)
df[["company", "year","total assets", "liabilities to assets (%)"]]

     company  year  total assets  liabilities to assets (%)
6      apple  2023        352583                  82.374079
7      apple  2024        364980                  84.396405
8      apple  2025        359241                  79.475338
0  microsoft  2023        411976                  49.942958
1  microsoft  2024        512163                  47.579774
2  microsoft  2025        619003                  44.510931
3      tesla  2023        106618                  40.339342
4      tesla  2024        122070                  39.641189
5      tesla  2025        137806                  39.868366

### Company Analysis

### Tesla: Financial Performance

From 2023 to 2025, Tesla experienced a significant decline in profitability. Revenue growth slowed and eventually turned negative, while its net profit margin dropped from 15.47% to 4.07%. However, its liabilities-to-assets ratio remained relatively stable at around 40%. These figures alone are insufficient to determine whether Tesla was experiencing serious financial difficulties.

### Microsoft: Financial Performance

Microsoft demonstrated consistent financial growth from 2023 to 2025. The increases in revenue, net income, and profit margin suggest that the company experienced business expansion while improving its profitability. However, these financial indicators alone are insufficient to determine which specific strategies contributed to this growth.

### Apple: Financial Performance

Apple demonstrated a decline followed by a recovery in profitability from 2023 to 2025. In 2024, revenue increased while the net profit margin declined. In 2025, however, revenue, net income, and net profit margin all increased, indicating a recovery in profitability. Nevertheless, the underlying causes of these changes cannot be determined from these financial figures alone.

### Comparative Conclusion

Overall, Microsoft, Tesla, and Apple demonstrated different financial trends from 2023 to 2025. Microsoft maintained consistent growth, Apple experienced a recovery in profitability after an initial decline, while Tesla experienced a significant decline in profitability. These differences highlight the importance of evaluating financial performance using multiple indicators, including revenue, net income, operating cash flow, and financial structure, rather than relying on a single metric.